version: "3"
services:
  deepstream:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../deepstream-src-appsrc/OCR/images:/deepstream/OCR/images
    environment:
      - IMAGE_PATH=/deepstream/OCR/images/ocr.png
    runtime: nvidia  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
            cpus: '0.50'
            memory: 1.5G
