#!/bin/bash
sudo docker run -itd --gpus all --runtime=nvidia -p 8000:8000 --cpus="0.50" --memory=1.5G  -v $PWD/../deepstream-src-appsrc/OCR/images:/deepstream/OCR/images -e IMAGE_PATH=/deepstream/OCR/images/ocr.png deepstream
